version: "3.3"
services:
  mongo:
    image: mongo
    ports: 
      - "27018:27017"
  account-service:
    #environment:
    build:
      context: account-service
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000"
  person-service:
    #environment:
    build:
      context: person-service
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000"
  gateway: 
    build: 
      context: gateway
    restart: always
    depends_on: 
      - account-service
      - person-service
    ports:
      - "8081:8080"