version: "3.3"
services:
  mongo:
    image: mongo
    ports: 
      - "27018:27017"
  account-service:
    #environment:
    build:
      context: account-service
    restart: always
    depends_on:
      - mongo
    ports:
      - "3000:3000"
  person-service:
    #environment:
    build:
      context: person-service
    restart: always
    depends_on:
      - mongo
    ports:
      - "3001:3000"